### ISSUE TITLE
docker image elixir:1.12.2-alpine compilation error

### ISSUE THREAD

**Issue by carlpartridge** [elixir-gettext/gettext#277]
It compiles just fine on my mac, but docker with elixir:1.12.2-alpine image fails with this error
```
#29 33.36 ==> gettext
#29 33.36 Compiling 1 file (.yrl)
#29 33.42 Compiling 1 file (.erl)
#29 33.60 Compiling 20 files (.ex)
#29 34.76
#29 34.76 == Compilation error in file lib/gettext/compiler.ex ==
#29 34.76 ** (Protocol.UndefinedError) protocol Enumerable not implemented for :info of type Atom
#29 34.76     (elixir 1.12.2) lib/enum.ex:1: Enumerable.impl_for!/1
#29 34.76     (elixir 1.12.2) lib/enum.ex:141: Enumerable.reduce/3
#29 34.76     (elixir 1.12.2) lib/enum.ex:403: Enum.any?/2
#29 34.76     (logger 1.12.2) lib/logger.ex:911: Logger.macro_log/4
#29 34.76     (logger 1.12.2) expanding macro: Logger.error/1
#29 34.76     lib/gettext/compiler.ex:356: Gettext.Compiler.warn_if_domain_contains_slashes/1
#29 34.76     (elixir 1.12.2) expanding macro: Kernel.if/2
#29 34.76     lib/gettext/compiler.ex:355: Gettext.Compiler.warn_if_domain_contains_slashes/1
#29 34.78 could not compile dependency :gettext, "mix compile" failed. You can recompile this dependency with "mix deps.compile gettext", update it with "mix deps.update gettext" or clean it with "mix deps.clean gettext"
```

versions (via mix hex.info):
```
#29 1.666 Hex:    0.21.2
#29 1.666 Elixir: 1.12.2
#29 1.671 OTP:    24.0.4
#29 1.671
#29 1.671 Built with: Elixir 1.11.4 and OTP 21.3
```

and rebar:
```
rebar 3.15.2 on Erlang/OTP 24 Erts 12.0.3
```

**Comment by josevalim** [comment]
Please check your logger configuration for config/prod.exs. I believe your compile_time_purge configuration or similar is wrong.

**Comment by carlpartridge** [comment]
Yup that seems to have been it, thank you so much for the quick response!
